import { StyleSheet } from "react-native";

export const css = StyleSheet.create({
    cont: {
        width: 428,
        marginLeft: 'auto',
        marginRight: 'auto',
        backgroundColor: '#2C92D2',
        fontFamily: 'Arial',
        height: '100%',
        minHeight: '100vh',
    },
    cont2: {
        width: 428,
        paddingTop: 212,
        marginLeft: 'auto',
        marginRight: 'auto',
        fontFamily: 'Arial',
        height: '100%',
        minHeight: '100vh',
        position: 'relative',
    },
    btn_yellow: {
        width: 300,
        height: 52,
        color: 'white',
        fontSize: 16,
        backgroundColor: '#F0BC08',
        borderRadius: 5,
        fontWeight: 'bold',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: 'auto',
        marginRight: 'auto',
    },
    ttl: {
        fontSize: 28,
        color: 'white',
        marginLeft: 'auto',
        marginRight: 'auto',
    },
    dsc: {
        fontSize: 15.5,
        color: '#E1FA08',
        marginLeft: 'auto',
        marginRight: 'auto',
    },
    input: {
        color: 'white',
        fontSize: 18,
        width: 300,
        height: 60,
        paddingLeft: 23,
        backgroundColor: '#ffffff33',
        borderRadius: 5,
        marginLeft: 'auto',
        marginRight: 'auto',
    }
});